image: python:3.8

pipelines:
  pull-requests:
    '**':
      - step:
          name: check target branch
          script:
            - if [ "${BITBUCKET_PR_DESTINATION_BRANCH}" != "dev" ] && [ "${BITBUCKET_PR_DESTINATION_BRANCH}" != "main"]; then printf "not a target branch we want to check"; exit; fi
            - printf 'running pipeline'
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - pytest
          services:
            - mongo

definitions:
  services:
    mongo:
      image: mongo
