image: python:3.8

pipelines:
  branches:
    main:
      - step:
          name: Lint and test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - black --check .
            - pytest
          services:
            - mongo
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git pull -r $DOWNSTREAM_REPO main || echo "main branch does not exist"
            - git push $DOWNSTREAM_REPO main

  pull-requests:
    '**':
      - step:
          name: Lint and test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - black --check .
            - pytest
          services:
            - mongo

  tags:
    "*v":
      - step:
          name: Lint and test
          caches:
            - pip
          script:
            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - black --check .
            - pytest
          services:
            - mongo
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git pull -r $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG does not exist"
            - git push $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG already exists"
      - step:
          name: Build docker image
          services:
            - docker
          script:
            - if [ -f Dockerfile ]; then printf "building docker image"; else printf "no Dockerfile found"; exit; fi
            # using the self-hosted container registry provided by https://github.com/tergite/tergite-registry
            # its domain is saved in CONTAINER_REGISTRY workspace secret variable in format domain.com:port
            # $DOCKER_USERNAME and $DOCKER_PASSWORD are also workspace secret variables
            - docker login ${CONTAINER_REGISTRY} -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker build -t ${CONTAINER_REGISTRY}/tergite-mss:$BITBUCKET_TAG .
            - docker push ${CONTAINER_REGISTRY}/tergite-mss:$BITBUCKET_TAG

definitions:
  services:
    mongo:
      image: mongo
