definitions:
  caches:
    cypress: ~/.cache
  steps:
    - step: &Test-and-lint-step
        name: Lint and test
        image: cypress/browsers:node18.12.0-chrome107
        caches:
          - cypress
        script:
          - npm i -g pnpm
          - pnpm i --frozen-lockfile
          - echo "EQUALITY_ERROR_MARGIN=$EQUALITY_ERROR_MARGIN" >> .env.test
          - pnpm run lint
          - pnpm run e2e
        artifacts:
          - .next/**

pipelines:
  pull-requests:
    '**':
      - step: *Test-and-lint-step

  tags:
    'v*':
      - step: *Test-and-lint-step
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git pull -r $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG does not exist"
            - git push $DOWNSTREAM_REPO $BITBUCKET_TAG || echo "tag $BITBUCKET_TAG already exists"

  branches:
    main:
      - step: *Test-and-lint-step
      - step:
          name: Push downstream
          script:
            - if [ "${SHOULD_PUSH_DOWNSTREAM}" != "true" ]; then printf "downstream push not enabled"; exit; fi
            - git pull -r $DOWNSTREAM_REPO main || echo "main branch does not exist"
            - git push $DOWNSTREAM_REPO main

