image: cypress/browsers:node18.12.0-chrome107

definitions:
    caches:
        cypress: ~/.cache

pipelines:
    pull-requests:
        '**':
            - step:
                  name: check target branch
                  script:
                      - if [ "${BITBUCKET_PR_DESTINATION_BRANCH}" != "dev" ] && [ "${BITBUCKET_PR_DESTINATION_BRANCH}" != "main"]; then printf "not a target branch we want to check"; exit; fi
                      - printf 'running pipeline'
            - step:
                  name: lint, build, test
                  caches:
                      - cypress
                      - node
                  script:
                      - npm ci
                      - npm run lint
                      - npm run e2e
                  artifacts:
                      - .next/**
    tags:
        '*':
            - step:
                  name: check for Dockerfile
                  script:
                      - if [ -f Dockerfile ]; then printf "building docker image"; else printf "no Dockerfile found"; exit; fi
            - step:
                  name: Build docker image
                  services:
                      - docker
                  script:
                      # using the self-hosted container registry provided by https://github.com/tergite/tergite-registry
                      # its domain is saved in CONTAINER_REGISTRY workspace secret variable in format domain.com:port
                      # $DOCKER_USERNAME and $DOCKER_PASSWORD are also workspace secret variables
                      - docker login ${CONTAINER_REGISTRY} -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                      - docker buildx create --name multi-platform-builder --bootstrap --use
                      - docker buildx build --platform linux/amd64,linux/arm64 -t ${CONTAINER_REGISTRY}/tergite-landing-page:$BITBUCKET_TAG --push .

