definitions:
    caches:
        cypress: ~/.cache

pipelines:
    default:
        - step:
              name: Lint and test
              image: cypress/browsers:node18.12.0-chrome107
              caches:
                  - cypress
              script:
                  - npm i -g pnpm
                  - pnpm i --frozen-lockfile
                  - pnpm run lint
                  - pnpm run e2e
              artifacts:
                  - .next/**
        # - step:
        #     name: Deploy artifacts using SCP to STAGING
        #     deployment: staging
        #     script:
        #       # You need to set up pipelines SSH keys first. Read https://support.atlassian.com/bitbucket-cloud/docs/set-up-pipelines-ssh-keys-on-linux/#Update-the-known-hosts
        #       - pipe: atlassian/scp-deploy:0.3.3
        #         variables:
        #           USER: $USER
        #           SERVER: $SERVER
        #           REMOTE_PATH: '/home/ahindura/repos/tergite-webgui'
        #           LOCAL_PATH: '.next/*'

