image: cypress/browsers:node18.12.0-chrome107

definitions:
    caches:
        cypress: ~/.cache

pipelines:
    pull-requests:
        '**':
            - step:
                  name: check target branch
                  script:
                      - if [ "${BITBUCKET_PR_DESTINATION_BRANCH}" != "dev" ] && [ "${BITBUCKET_PR_DESTINATION_BRANCH}" != "main"]; then printf "not a target branch we want to check"; exit; fi
                      - printf 'running pipeline'
            - step:
                  name: lint, build, test
                  caches:
                      - cypress
                      - npm
                  script:
                      - npm run lint
                      - npm run e2e
                  artifacts:
                      - .next/**
    tags:
        '*':
            - step:
                  name: check for Dockerfile
                  script:
                      - if [ -f Dockerfile ]; then printf "building docker image"; else printf "no Dockerfile found"; exit; fi
            - step:
                  name: Build docker image
                  caches:
                      - npm
                  script:
                      # using the single private repo available to every free docker account
                      # $DOCKER_USERNAME and $DOCKER_PASSWORD are a custom bitbucket secrets
                      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                      - docker build -t tergite-qal9000:$BITBUCKET_TAG .
                      - docker push tergite-qal9000:$BITBUCKET_TAG
                      - docker tag tergite-qal9000:$BITBUCKET_TAG tergite-qal9000:latest
                      - docker push tergite-qal9000:latest

