---
version: "3"

services:
  landing-page:
    restart: always
***REMOVED***
    labels:
      name: "landing-page"
    logging:
      driver: "journald"
      options:
        labels: "name"
        env: "ENVIRONMENT"
    ports:
      - "8030:80"
    env_file:
      - .env

  mss:
    restart: always
***REMOVED***
    labels:
      name: "mss"
    logging:
      driver: "journald"
      options:
        labels: "name"
        env: "ENVIRONMENT"
    ports:
      - "8002:80"
    env_file:
      - .env

  web-gui:
    restart: always
***REMOVED***
    labels:
      name: "web-gui"
    logging:
      driver: "journald"
      options:
        labels: "name"
        env: "ENVIRONMENT"
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://mss/v2
    env_file:
      - .env

  loki-promtail:
    restart: always
    image: grafana/promtail:2.8.3
    labels:
      name: "promtail"
    logging:
      driver: "journald"
      options:
        labels: "name"
        env: "ENVIRONMENT"
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/journal:/var/log/journal
      - /run/log/journal:/run/log/journal
    command: "-config.expand-env=true -config.file=/etc/promtail/config.yaml"
    env_file:
      - .env
