---
version: "3"

services:
  landing-page:
    restart: always
    depends_on:
      - mss
    image: "${REGISTRY}/tergite-landing-page:${LANDING_PAGE_VERSION:-v0.1.1}"
    logging:
      driver: ${LOGGING_DRIVER}
    ports:
      - "8030:80"
    environment:
      - API_BASE_URL=http://mss
      - MSS_CONFIG_FILE=/app/mss-config.toml
    volumes:
      - ./mss-config.toml:/app/mss-config.toml:ro
    env_file:
      - .env

  mss:
    restart: always
    image: "${REGISTRY}/tergite-mss:${MSS_VERSION:-v0.4.0}"
    logging:
      driver: ${LOGGING_DRIVER}
    ports:
      - "8002:80"
    environment:
      - MSS_CONFIG_FILE=/code/mss-config.toml
    volumes:
      - ./mss-config.toml:/code/mss-config.toml:ro
    env_file:
      - .env

  webgui:
    restart: always
    depends_on:
      - mss
    image: "${REGISTRY}/tergite-webgui:${WEBGUI_VERSION:-v0.0.4}"
    logging:
      driver: ${LOGGING_DRIVER}
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URL=http://mss
      - MSS_CONFIG_FILE=/app/mss-config.toml
    volumes:
      - ./mss-config.toml:/app/mss-config.toml:ro
    env_file:
      - .env

  loki-promtail:
    restart: always
    image: grafana/promtail:${PROMTAIL_VERSION:-2.8.3}
    logging:
      driver: ${LOGGING_DRIVER}
    volumes:
      - ./promtail.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data/promtail:/tmp
    command: "-config.expand-env=true -config.file=/etc/promtail/config.yaml"
    env_file:
      - .env
