#[REST_API_MAP]
#web-gui = "/web-gui"
#device_config = "/web-gui/config"

[PORTS]
WS_PORT = 6532

[ENDPOINTS_URL]
pingu = "http://localhost:9090"
loke = "http://localhost:9000"
lokea = "http://localhost:8090"

#[SERVER]
#WS_HOST = "ws://localhost:"


[TIMEOUTS]
#REQUEST_TIMEOUT = 10
ENDPOINT_FETCH_TIMEOUT = 10
