name: Dashboard CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "20"
          - "21"
          - "22"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint
        run: |
          npm ci
          npm run lint
      - name: Component tests
        run: npm run test
      - name: End-to-end tests
        run: |
          echo "TEST_THRESHOLD=${{ vars.TEST_THRESHOLD }}" >> .env.test
          npm run e2e
