name: Frontend CI
# the CI for the whole front end monorepo

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  # TODO: Add a stage for testing the docker compose loading
  upstream:
    name: Update upstream
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && vars.SHOULD_PUSH_UPSTREAM == 'true' }}
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v4

      - name: Push upstream
        run: |
          if [ "${{ github.event_name }}" != "push" ] || [ "${{ vars.SHOULD_PUSH_UPSTREAM }}" != 'true' ]; then printf "upstream not enabled"; exit; fi
          git config user.email ${{ secrets.UPSTREAM_USER }}
          git pull -r ${{ secrets.UPSTREAM_REPO }} ${{ github.ref_name }} || echo "${{ github.ref_name }} does not exist"
          git push ${{ secrets.UPSTREAM_REPO }} ${{ github.ref_name }} || echo "${{ github.ref_name }} already exists"

# FIXME: Add a smoke test for testing building with docker compose
